
paths:
  /morelocal/letters:
    get:
      tags:
        - More Local
      summary: 로컬레터 목록 조회
      responses:
        '200':
          description: 로컬레터 목록 조회 성공
          schema:
            type: object
            properties:
              isSuccess:
                type: boolean
                example: true
              code:
                type: integer
                example: 2000
              message:
                type: string
                example: "SUCCESS!"
              result:
                type: array
                example: {
                  "letters": [
                    {
                      "letter_id": 7,
                      "category": "뉴스레터",
                      "title": "제목8",
                      "thumbnail_url": "https://image.png",
                      "created_at": "2024.08.02"
                    },
                    {
                      "letter_id": 6,
                      "category": "인터뷰",
                      "title": "제목7",
                      "thumbnail_url": "https://image.png",
                      "created_at": "2024.08.02"
                    },
                    {
                      "letter_id": 5,
                      "category": "인터뷰",
                      "title": "제목6",
                      "thumbnail_url": "https://image.png",
                      "created_at": "2024.08.02"
                    },
                    {
                      "letter_id": 4,
                      "category": "뉴스레터",
                      "title": "제목5",
                      "thumbnail_url": "https://image.png",
                      "created_at": "2024.08.02"
                    },
                    {
                      "letter_id": 3,
                      "category": "인터뷰",
                      "title": "제목4",
                      "thumbnail_url": "https://image.png",
                      "created_at": "2024.08.02"
                    },
                    {
                      "letter_id": 2,
                      "category": "인터뷰",
                      "title": "제목3",
                      "thumbnail_url": "https://image.png",
                      "created_at": "2024.08.02"
                    },
                    {
                      "letter_id": 1,
                      "category": "뉴스레터",
                      "title": "제목2",
                      "thumbnail_url": "https://image.png",
                      "created_at": "2024.08.02"
                    },
                    {
                      "letter_id": 0,
                      "category": "인터뷰",
                      "title": "제목1",
                      "thumbnail_url": "https://image.png",
                      "created_at": "2024.08.02"
                    }
                  ]
                }
  /morelocal/letters/{letterId}:
    get:
      tags:
        - More Local
      summary: 로컬레터 상세 조회
      parameters:
        - name: letterId
          type: integer
          in: path
          schema:
            type: integer
            description: 로컬레터 id
          required: true
      responses:
        '200':
          description: 로컬레터 상세 조회 성공
          schema:
            type: object
            properties:
              isSuccess:
                type: boolean
                example: true
              code:
                type: integer
                example: 2000
              message:
                type: string
                example: "SUCCESS!"
              result:
                type: array
                example: {
                  "letter": {
                    "letter_id": 0,
                    "category": "인터뷰",
                    "title": "제목",
                    "thumbnail_url": "https://image.png",
                    "created_at": "2024.08.02",
                    "content": "내용"
                  }
                }
        '400':
          description: 파라미터 오류 (존재하지 않는 id값)
          schema:
            type: object
            properties:
              isSuccess:
                type: boolean
                example: false
              code:
                type: string
                example: LETTER4001
              message:
                type: string
                example: 존재하지 않는 로컬레터입니다.       
  /morelocal/letters/recent:
    get:
      tags:
        - More Local
      summary: 로컬레터 최근 업데이트된 글 6개 조회
      responses:
        '200':
          description: 로컬레터 상세 조회 성공
          schema:
            type: object
            properties:
              isSuccess:
                type: boolean
                example: true
              code:
                type: integer
                example: 2000
              message:
                type: string
                example: "success!"
              result:
                type: array
                example: {
                  "letters": [
                    {
                      "letter_id": 7,
                      "title": "제목8",
                      "thumbnail_url": "https://image.png"
                    },
                    {
                      "letter_id": 6,
                      "title": "제목7",
                      "thumbnail_url": "https://image.png"
                    },
                    {
                      "letter_id": 5,
                      "title": "제목6",
                      "thumbnail_url": "https://image.png"
                    },
                    {
                      "letter_id": 4,
                      "title": "제목5",
                      "thumbnail_url": "https://image.png"
                    },
                    {
                      "letter_id": 3,
                      "title": "제목4",
                      "thumbnail_url": "https://image.png"
                    },
                    {
                      "letter_id": 2,
                      "title": "제목3",
                      "thumbnail_url": "https://image.png"
                    }
                  ]
                }
  /morelocal/events:
    get:
      tags:
        - More Local
      summary: 이벤트 목록 조회
      responses:
        '200':
          description: 이벤트 목록 조회 성공
          schema:
            type: object
            properties:
              isSuccess:
                type: boolean
                example: true
              code:
                type: integer
                example: 2000
              message:
                type: string
                example: "SUCCESS!"
              result:
                type: array
                example: {
                  "events": [
                    {
                      "event_id": 6,
                      "subregion_name": "중구",
                      "title": "제목7",
                      "thumbnail_url": "https://image.png",
                      "created_at": "2024.08.02",
                      "start_date": "2024.08.02",
                      "end_date": "2024.11.02"
                    },
                    {
                      "event_id": 3,
                      "subregion_name": "중구",
                      "title": "제목4",
                      "thumbnail_url": "https://image.png",
                      "created_at": "2024.08.02",
                      "start_date": "2024.08.02",
                      "end_date": "2024.10.02"
                    },
                    {
                      "event_id": 2,
                      "subregion_name": "서대문구",
                      "title": "제목3",
                      "thumbnail_url": "https://image.png",
                      "created_at": "2024.08.02",
                      "start_date": "2024.08.02",
                      "end_date": "2024.11.02"
                    },
                    {
                      "event_id": 0,
                      "subregion_name": "서대문구",
                      "title": "제목1",
                      "thumbnail_url": "https://image.png",
                      "created_at": "2024.08.02",
                      "start_date": "2024.08.02",
                      "end_date": "2024.10.02"
                    }
                  ]
                }
  /morelocal/events/{eventId}:
    get:
      tags:
        - More Local
      summary: 이벤트 상세 조회
      parameters:
        - name: eventId
          type: integer
          in: path
          schema:
            type: integer
            description: 이벤트 id
          required: true
      responses:
        '200':
          description: 이벤트 상세 조회 성공
          schema:
            type: object
            properties:
              isSuccess:
                type: boolean
                example: true
              code:
                type: integer
                example: 2000
              message:
                type: string
                example: "SUCCESS!"
              result:
                type: array
                example: {
                  "event": {
                    "event_id": 0,
                    "subregion_name": "중구",
                    "title": "제목",
                    "thumbnail_url": "https://image.png",
                    "created_at": "2024.07.02",
                    "start_date": "2024.08.02",
                    "end_date": "2024.10.02",
                    "content": "내용"
                  }
                }
        '400':
          description: 파라미터 오류 (존재하지 않는 id값)
          schema:
            type: object
            properties:
              isSuccess:
                type: boolean
                example: false
              code:
                type: string
                example: EVENT4001
              message:
                type: string
                example: 존재하지 않는 이벤트입니다.    
  /morelocal/events/recent:
    get:
      tags:
        - More Local
      summary: 이벤트 최근 업데이트된 글 6개 조회
      responses:
        '200':
          description: 로컬레터 상세 조회 성공
          schema:
            type: object
            properties:
              isSuccess:
                type: boolean
                example: true
              code:
                type: integer
                example: 2000
              message:
                type: string
                example: "SUCCESS!"
              result:
                type: array
                example: {
                  "events": [
                    {
                      "event_id": 7,
                      "title": "제목8",
                      "thumbnail_url": "https://image.png"
                    },
                    {
                      "event_id": 6,
                      "title": "제목7",
                      "thumbnail_url": "https://image.png"
                    },
                    {
                      "event_id": 5,
                      "title": "제목6",
                      "thumbnail_url": "https://image.png"
                    },
                    {
                      "event_id": 4,
                      "title": "제목5",
                      "thumbnail_url": "https://image.png"
                    },
                    {
                      "event_id": 3,
                      "title": "제목4",
                      "thumbnail_url": "https://image.png"
                    },
                    {
                      "event_id": 2,
                      "title": "제목3",
                      "thumbnail_url": "https://image.png"
                    }
                  ]
                }